package com.app.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a staff member entity in the system. This entity is mapped to the
 * "staff" table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Staff {

	/**
	 * Unique identifier for the staff member. This field is auto-generated by the
	 * database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * Name of the staff member.
	 */
	private String name;

	/**
	 * Detailed information about the staff member.
	 */
	private String details;

	/**
	 * ID of the service associated with the staff member.
	 */
	private Long serviceId;

	/**
	 * Gender of the staff member. This field is stored as a string in the database.
	 */
	@Enumerated(EnumType.STRING)
	private Gender gender;
}
