package com.app.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a user in the system. Mapped to the 'users' table
 * in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Users {

	/**
	 * Unique identifier for the user. Automatically generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * Name of the user. This field is mandatory and cannot be null.
	 */
	@Column(nullable = false)
	private String name;

	/**
	 * Email address of the user. This field is unique and mandatory.
	 */
	@Column(unique = true, nullable = false)
	private String email;

	/**
	 * Mobile number of the user. This field is mandatory and cannot be null.
	 */
	@Column(nullable = false)
	private String mobileNo;

	/**
	 * Password of the user. This field is mandatory and cannot be null.
	 */
	@Column(nullable = false)
	private String password;

	/**
	 * Gender of the user. This field is mandatory and cannot be null.
	 */
	@Column(nullable = false)
	private String gender;
}
